--.PIXELPULSEGAMING_PRODUCTOS
Insert into PIXELPULSEGAMING_PRODUCTOS (IDPRODUCTO,NOMBREPRODUCTO,PRECIO,CATEGORIA_ID,DESCRIPCION) values ('1','Notebook Asus Gamer ROG Strix G16','100','1','Intel Core i9 13va Generacion 24 Nucleos NVIDIA GeForce RTX 4060 16GB RAM 512GB SSD 16 FHD+ 165Hz');
Insert into PIXELPULSEGAMING_PRODUCTOS (IDPRODUCTO,NOMBREPRODUCTO,PRECIO,CATEGORIA_ID,DESCRIPCION) values ('2','G6 GIGABYTE RTX 4060 i7','100','1','i7 13va 8GB 512GB SSD 16 FHD 165Hz Notebook Intel Core');
Insert into PIXELPULSEGAMING_PRODUCTOS (IDPRODUCTO,NOMBREPRODUCTO,PRECIO,CATEGORIA_ID,DESCRIPCION) values ('3','EVGA X17 Gaming Mouse','100','2','8k, Wired, Grey, Customizable, 16,000 DPI, 5 Profiles, 10 Buttons, Ergonomic 903-W1-17GR-KR');
Insert into PIXELPULSEGAMING_PRODUCTOS (IDPRODUCTO,NOMBREPRODUCTO,PRECIO,CATEGORIA_ID,DESCRIPCION) values ('4','Mouse Gamer EVGA X12','52240','2','Cableado, Ambidiestro, Dual Sensor, 16000 DPI, Color Blanco');
Insert into PIXELPULSEGAMING_PRODUCTOS (IDPRODUCTO,NOMBREPRODUCTO,PRECIO,CATEGORIA_ID,DESCRIPCION) values ('5','Procesador Intel i9-13900K','731495','3','3Ghz Turbo 5.8Ghz, LGA1700, 8-Core / 32-Threads');
Insert into PIXELPULSEGAMING_PRODUCTOS (IDPRODUCTO,NOMBREPRODUCTO,PRECIO,CATEGORIA_ID,DESCRIPCION) values ('6','Ryzen 5 8600G (AM5)','316690','3','6 núcleos, 12 hilos 8.6 Ghz');
Insert into PIXELPULSEGAMING_PRODUCTOS (IDPRODUCTO,NOMBREPRODUCTO,PRECIO,CATEGORIA_ID,DESCRIPCION) values ('7','Tarjeta de Video Gigabyte Radeon RX6900XT','2871000','4','Gaming OC 16G 4K GDDR6 PCle 4.0 [ GV-R69XTGAMINGOC-16GD ]');
Insert into PIXELPULSEGAMING_PRODUCTOS (IDPRODUCTO,NOMBREPRODUCTO,PRECIO,CATEGORIA_ID,DESCRIPCION) values ('8','EVGA GeForce RTX 3080','1462990','4','12GB FTW3 ULTRA GAMING [12G-P5-4877-KL]');
Insert into PIXELPULSEGAMING_PRODUCTOS (IDPRODUCTO,NOMBREPRODUCTO,PRECIO,CATEGORIA_ID,DESCRIPCION) values ('9','Silla Gamer Cougar Armor One EVA','314895','5','PVC, Ajustable, 120kg, Negra-Rosado');
Insert into PIXELPULSEGAMING_PRODUCTOS (IDPRODUCTO,NOMBREPRODUCTO,PRECIO,CATEGORIA_ID,DESCRIPCION) values ('10','Silla Gamer Trust GXT 716 Rizza RGB','100403','5','Estilo y ambiente a tu configuración de juego. Estructura soporta hasta 120 kg.');
Insert into PIXELPULSEGAMING_PRODUCTOS (IDPRODUCTO,NOMBREPRODUCTO,PRECIO,CATEGORIA_ID,DESCRIPCION) values ('11','Monitor Gamer 27"','343590','6','TUF - QHD, Panel IPS, 165Hz(1ms)');
Insert into PIXELPULSEGAMING_PRODUCTOS (IDPRODUCTO,NOMBREPRODUCTO,PRECIO,CATEGORIA_ID,DESCRIPCION) values ('12','Monitor Gamer 27" Curvo Optix','338190','6','QHD, Panel VA, 165Hz(1ms), FreeSync Premium (G271CQR)');

--.PIXELPULSEGAMING_CATEGORIAS
Insert into PIXELPULSEGAMING_CATEGORIAS (IDCATEGORIA,NOMBRECATEGORIA) values ('1','Notebooks');
Insert into PIXELPULSEGAMING_CATEGORIAS (IDCATEGORIA,NOMBRECATEGORIA) values ('2','Periféricos');
Insert into PIXELPULSEGAMING_CATEGORIAS (IDCATEGORIA,NOMBRECATEGORIA) values ('3','Procesadores');
Insert into PIXELPULSEGAMING_CATEGORIAS (IDCATEGORIA,NOMBRECATEGORIA) values ('4','Tarjetas de Video');
Insert into PIXELPULSEGAMING_CATEGORIAS (IDCATEGORIA,NOMBRECATEGORIA) values ('5','Sillas Gamer');
Insert into PIXELPULSEGAMING_CATEGORIAS (IDCATEGORIA,NOMBRECATEGORIA) values ('6','Monitores');
