# Generated by Django 5.0.4 on 2024-04-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixelpulsegaming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='descripcion',
            field=models.CharField(default='null', max_length=250, verbose_name='Descripción del producto'),
            preserve_default=False,
        ),
    ]
