# Generated by Django 5.0.4 on 2024-04-28 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pixelpulsegaming', '0002_productos_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
